
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO inviwo/sgct
    REF 049c0f78fe372e6262e004c2f02b898f3c935ba3
    SHA512 86cb8c1d293e7502b279119bcc55d6f20c75687ead64ec661aedb8f82744704e849d3a9ac1ad524f8b75eda92e3b5c13acc67859caccb09e257b0302e6476465
    HEAD_REF masterBS
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        freetype       SGCT_FREETYPE_SUPPORT
        openvr         SGCT_OPENVR_SUPPORT
        spout2         SGCT_SPOUT_SUPPORT
        tracy          SGCT_TRACY_SUPPORT
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -DSGCT_INSTALL=ON
        -DSGCT_BUILD_TESTS=OFF
        -DSGCT_EXAMPLES=OFF
        -DSGCT_VRPN_SUPPORT=OFF
        -DSGCT_ENABLE_EDIT_CONTINUE=OFF
        -DSGCT_MEMORY_PROFILING=OFF

        -DSGCT_DEP_INCLUDE_CATCH2=OFF
        -DSGCT_DEP_INCLUDE_FMT=OFF
        -DSGCT_DEP_INCLUDE_FREETYPE=OFF
        -DSGCT_DEP_INCLUDE_GLAD=OFF
        -DSGCT_DEP_INCLUDE_GLFW=OFF
        -DSGCT_DEP_INCLUDE_GLM=OFF
        -DSGCT_DEP_INCLUDE_JSON=OFF
        -DSGCT_DEP_INCLUDE_JSON_VALIDATOR=OFF
        -DSGCT_DEP_INCLUDE_LIBPNG=OFF
        -DSGCT_DEP_INCLUDE_OPENVR=OFF
        -DSGCT_DEP_INCLUDE_SCN=OFF
        -DSGCT_DEP_INCLUDE_STB=OFF
        -DSGCT_DEP_INCLUDE_TINYXML=OFF
        -DSGCT_DEP_INCLUDE_TRACY=OFF
        -DSGCT_DEP_INCLUDE_VRPN=OFF
        -DSGCT_DEP_INCLUDE_ZLIB=OFF

        ${FEATURE_OPTIONS}
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH share/sgct) 

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")
