uniform float value = 1;
writeonly uniform image2D dest;

layout (local_size_x = 16, local_size_y = 16) in;
void main(){
    ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);

    vec2 texCoord = vec2(gl_GlobalInvocationID.xy) / 512.0;

    float localCoef = length(vec2(ivec2(gl_LocalInvocationID.xy)-8)/8.0);
    float globalCoef = sin(float(gl_WorkGroupID.x+gl_WorkGroupID.y)*0.1 + value)*0.5;

    imageStore(dest, storePos, vec4(globalCoef*localCoef , 0.0, 0.0, 0.0)); 
}