name: 'Configure Inviwo Build environment'
description: 'Configure vcpkg and ccache'

inputs:
  triplet:
    description: 'Vcpkg triplet to use'
    required: true
  configuration:
    description: 'Configuration to use'
    required: true
  ccache:
    description: 'Setup ccache'
    required: false
    default: true
  gh-token:
    description: "github actions token for access to the octokit api to be able to remove old caches"
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: "Setup MSVC"
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: "Get Vcpkg SHA"
      shell: bash
      run: |
        SHA=`jq -r '.["vcpkg-configuration"].["default-registry"].baseline' inviwo/vcpkg.json`
        echo "VCPKG_SHA=${SHA}" >> $GITHUB_ENV

    - name: "Clone Vcpkg"
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        ref: ${{ env.VCPKG_SHA }}
        fetch-depth: 0
        path: vcpkg

    - name: "VCPKG Update"
      shell: bash
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.sh
        echo "VCPKG_INSTALLATION_ROOT=`pwd`" >> $GITHUB_ENV
        echo "VCPKG_ROOT=`pwd`" >> $GITHUB_ENV

    - name: "Create ccache directory"
      shell: bash
      run: |
        mkdir ccache-debug

    - name: "Setup Ccache"
      id: ccache
      if: inputs.ccache
      uses: petersteneteg/ccache-action@v2.4.0
      with:
        variant: ccache
        max-size: "1500M"
        verbose: 2
        save: "${{ github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'CI: Debug') }}"
        append-timestamp: true
        gh-token: ${{ inputs.gh-token }}
        key: inviwo-${{ inputs.triplet }}-${{ inputs.configuration }}
        restore-keys: |
          inviwo-${{ inputs.triplet }}-${{ inputs.configuration }}

    - name: "Configure Ccache Debug"
      if: "${{ contains( github.event.pull_request.labels.*.name, 'CI: Cache Debug') }}"
      shell: bash
      run: |
          echo "CCACHE_DEBUG=true" >> $GITHUB_ENV
          echo "CCACHE_LOGFILE=${{ github.workspace }}/ccache-debug/ccache.log" >> $GITHUB_ENV
          echo "CCACHE_DEBUGDIR=${{ github.workspace }}/ccache-debug" >> $GITHUB_ENV

    - name: "Copy ccache"
      shell: bash
      if: runner.os == 'Windows' && inputs.ccache
      run: |
        mkdir build
        cp ${{ steps.ccache.outputs.executable }} build/cl.exe

    - name: "Install Latest CMake"
      shell: bash
      if: runner.os == 'Linux'
      run: |
        # Get the latest CMake version from the GitHub API
        CMAKE_VERSION=$(curl -s https://api.github.com/repos/Kitware/CMake/releases/latest | grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/')
        echo "Latest CMake version: $CMAKE_VERSION"

        curl -L -o install_cmake.sh https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh
        chmod +x install_cmake.sh
        sudo ./install_cmake.sh --skip-license --prefix=/usr/local

        echo "Path to CMAKE $(which cmake)"
        echo "Installed CMake version:"
        cmake --version

    - name: "Install AppImageTool"
      shell: bash
      if: runner.os == 'Linux'
      run: |
        curl -L -o appimagetool.AppImage https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool.AppImage
        sudo mv appimagetool.AppImage /usr/local/bin/appimagetool