/***************************************************************************************************
 * This file is auto-generated by colormaps-to-cpp.py — do not edit.
 * Source data: Scientific colour maps by Fabio Crameri
 * https://www.fabiocrameri.ch/colourmaps/
 **************************************************************************************************/

/**********************************************************************************
 * Copyright (c) 2012-2026 Inviwo Foundation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation and/or
 * other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *********************************************************************************/

#pragma once

#include <span>
#include <string_view>

#include <inviwo/core/common/inviwocoredefine.h>
#include <fmt/format.h>
#include <glm/vec3.hpp>

namespace inviwo::scm {

enum class Continuous {
    acton,
    bam,
    bamO,
    bamako,
    batlow,
    batlowK,
    batlowW,
    berlin,
    bilbao,
    broc,
    brocO,
    buda,
    bukavu,
    cork,
    corkO,
    davos,
    devon,
    fes,
    glasgow,
    grayC,
    hawaii,
    imola,
    lajolla,
    lapaz,
    lipari,
    lisbon,
    managua,
    navia,
    naviaW,
    nuuk,
    oleron,
    oslo,
    roma,
    romaO,
    tofino,
    tokyo,
    turku,
    vanimo,
    vik,
    vikO
};

enum class Cyclic {
    bamO,
    brocO,
    corkO,
    romaO,
    vikO
};

enum class DiscreteSize {
    N10,
    N25,
    N50,
    N100
};

enum class Discrete {
    acton,
    bam,
    bamO,
    bamako,
    batlow,
    batlowK,
    batlowW,
    berlin,
    bilbao,
    broc,
    brocO,
    buda,
    bukavu,
    cork,
    corkO,
    davos,
    devon,
    fes,
    glasgow,
    grayC,
    hawaii,
    imola,
    lajolla,
    lapaz,
    lipari,
    lisbon,
    managua,
    navia,
    naviaW,
    nuuk,
    oleron,
    oslo,
    roma,
    romaO,
    tofino,
    tokyo,
    turku,
    vanimo,
    vik,
    vikO
};

enum class Categorical {
    acton,
    bamako,
    batlow,
    batlowK,
    batlowW,
    bilbao,
    buda,
    davos,
    devon,
    glasgow,
    grayC,
    hawaii,
    imola,
    lajolla,
    lapaz,
    lipari,
    navia,
    naviaW,
    nuuk,
    oslo,
    tokyo,
    turku
};

IVW_CORE_API std::span<const glm::vec3> get(Continuous type);
IVW_CORE_API std::span<const glm::vec3> get(Cyclic type);
IVW_CORE_API std::span<const glm::vec3> get(Discrete type, DiscreteSize size);
IVW_CORE_API std::span<const glm::vec3> get(Categorical type);

IVW_CORE_API std::span<const Continuous> allContinuous();
IVW_CORE_API std::span<const Cyclic> allCyclic();
IVW_CORE_API std::span<const DiscreteSize> allDiscreteSize();
IVW_CORE_API std::span<const Discrete> allDiscrete();
IVW_CORE_API std::span<const Categorical> allCategorical();

// fmt support
IVW_CORE_API std::string_view format_as(Continuous v);
IVW_CORE_API std::string_view format_as(Cyclic v);
IVW_CORE_API std::string_view format_as(DiscreteSize v);
IVW_CORE_API std::string_view format_as(Discrete v);
IVW_CORE_API std::string_view format_as(Categorical v);

}  // namespace inviwo::scm
