name: CMake

on: [push]

env:
  BUILD_TYPE: Release
  VCPKG_SHA: '18ab4b72a26284f0df28295ce7bf9b21c96f20f4'
  VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'                                   # recognized by vcpkg
  VCPKG_BINARY_SOURCES : 'files,${{ github.workspace }}/vcpkg-cache,readwrite'  # recognized by vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cache Vcpkg
      uses: inviwo/cache@v3
      with:
        path: |
          vcpkg
          !vcpkg/buildtrees
          !vcpkg/packages
          !vcpkg/download
        key: 'vcpkg-${{ env.VCPKG_SHA }}'  
  
    - name: Cache Vcpkg binaries
      uses: inviwo/cache@v3
      with:
        path: 'vcpkg-cache'
        key: 'vcpkg-bin-cache'
  
    - name: VCPKG Clone
      uses: actions/checkout@v2.3.2
      with:
        repository: 'microsoft/vcpkg'
        ref: ${{ env.VCPKG_SHA }}
        path: vcpkg
    
    - name: VCPKG Bootstrap
      shell: bash
      working-directory: vcpkg
      run: 'bootstrap-vcpkg.sh'
    
    - name: VCPKG Install
      shell: bash
      working-directory: vcpkg
      run: > 
        vcpkg install 
        fmt glm zlib assimp benchmark cimg freetype glew glfw3 glm gtest
  
    # qt5[core,svg] assimp benchmark cimg eigen3 fmt freetype glew glfw3 glm gtest hdf5[cpp,zlib] libjpeg-turbo 
    # libpng minizip nlohmann-json openexr pybind11 python3 tclap tiff tinydir tinyxml2 utfcpp zlib
     
    - uses: actions/checkout@v2
      with: 
        path: inviwo
        submodules: recursive
        
    #- name: Configure CMake
    #  shell: bash
    #  run: >
    #    cmake -S inviwo -B build 
    #      -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
    #      -DVCPKG_TARGET_TRIPLET='x64-windows-static'
    #      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          
    #- name: Build
    #  working-directory: build
    #  shell: bash
    #  run: cmake --build . --config $BUILD_TYPE
