name: CMake

on: [push]

env:
  BUILD_TYPE: Release
  VCPKG_SHA: '18ab4b72a26284f0df28295ce7bf9b21c96f20f4'
  VCPKG_TRIPLET: 'x64-windows-static'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cache Vcpkg
      uses: actions/cache@v2
      with:
        path: |
          vcpkg
          !vcpkg/buildtrees
          !vcpkg/packages
          !vcpkg/download
        key: 'vcpkg-${{ env.VCPKG_SHA }}'  
  
    - name: Cache Vcpkg binaries
      uses: actions/cache@v2
      with:
        path: 'vcpkg-cache'
        key: 'vcpkg-${{ env.VCPKG-TRIPLET }}-${{ env.VCPKG_SHA }}'  
  
    - name: VCPKG Clone
      uses: actions/checkout@v2.3.2
      with:
        repository: 'microsoft/vcpkg'
        ref: ${{ env.VCPKG_SHA }}
        path: vcpkg
    
    - name: VCPKG Bootstrap
      shell: bash
      working-directory: vcpkg
      run: 'bootstrap-vcpkg.sh'
    
    - name: VCPKG Install
      shell: bash
      working-directory: vcpkg
      run: > 
        vcpkg --binarysource=files,${{ github.workspace }}/vcpkg-cache 
        install fmt glm zlib
  
    # qt5[core,tools,svg] assimp benchmark cimg eigen3 fmt freetype glew glfw3 glm gtest hdf5[cpp,zlib] libjpeg-turbo 
    # libpng minizip nlohmann-json openexr pybind11 python3 tclap tiff tinydir tinyxml2 utfcpp zlib
     
    - uses: actions/checkout@v2
      with: 
        path: inviwo
        submodules: recursive
        
    - name: Configure CMake
      shell: bash
      run: >
        cmake -S inviwo -B build 
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET='x64-windows-static'
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          
    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
